import Head from 'next/head';
import Layout from '../Component/Layout';
import styles from '../styles/Home.module.css';

export default function News() {
  return (
    <div>
      <Layout>
        <Head>
          <title>Sports Page</title>
        </Head>
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
        </div>
      </Layout>
    </div>
  );
}
