import { match } from 'assert';
import Head from 'next/head';
import Layout from '../Component/Layout';
import styles from '../styles/Home.module.css';

export default function Sports() {
  return (
    <div>
      <Layout>
        <Head>
          <title>Sports Page</title>
        </Head>
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>

          <main>
            <div>
              <h2>Matches</h2>

              <table>
                <tr>
                  <th>Date</th>
                  <th>Day</th>

                  <th>Time</th>
                  <th>Sport</th>
                  <th>Event</th>
                  <th>Location</th>
                </tr>
                <tr>
                  <td>{match.date}</td>
                  <td>{match.time}</td>
                  <td>{match.matchname}</td>
                  <td>{match.location}</td>
                </tr>
              </table>
            </div>
          </main>
        </div>
      </Layout>
    </div>
  );
}
